In [9]:
import numpy as np

A = np.array([[0,1],[2,3],[4,5]])

B = np.array([[0,1,2,3],[4,5,6,7]])

C = np.dot(A,B)

print("行列A×Bの結果:")
print(C)

max_value = C.max()
print("最大値:",max_value)

行列A×Bの結果:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
最大値: 47
